version: '3'
services:
  landing-page-nowe:
    build: .
    container_name: "${CONTAINER_NAME}"
    volumes:
      - ./.next:/home/landingPage/.next
    ports:
      - "${CONTAINER_PORT}:3000"
    env_file:
      - .env
    command: npm start
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork: