version: '3'
services:
  landing-page-nowe:
    build: .
    container_name: "${CONTAINER_NAME}"
    volumes:
      - .:/home/landingPage
    ports:
      - "${CONTAINER_PORT}:3000"
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork: